version: '3'
services:
  web:
    image: "ahskhan/sparta-app-dockerised:v2"
    build: .
    command: "node app.js"
    ports:
      - "3000:3000"
    depends_on:
    - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports: 
      - "1234:1234"